@startuml
start
:学生登录系统;
:进入学生界面;
:查看考试列表;
if (是否有可参加的考试?) then (是)
    :选择要参加的考试;
    :点击开始考试;
    :答题;
    if (是否完成答题?) then (是)
        :点击提交试卷;
        if (考试时间是否结束?) then (是)
            :系统自动提交试卷;
        endif
        :教师批改成绩;
        :系统公布成绩;
        :学生查看成绩;
    else (否)
        :继续答题;
    endif
else (否)
    :提示暂无可参加的考试;
    stop
endif
stop
@enduml