@startuml
start
:用户输入分配或回收请求;
if (请求类型为分配) then (是)
    :选择分配算法;
    :调用分配函数;
    if (找到合适分区) then (是)
        :分割分区，更新已分配和空闲列表;
        :更新界面显示;
    else (否)
        :提示内存分配失败;
    endif
else (否)
    :输入要释放的进程 ID;
    :调用释放函数;
    :将指定进程占用的内存块标记为空闲;
    :合并相邻的空闲块;
    :更新界面显示;
endif
stop
@enduml